import { readFile, readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
import { parse } from 'yaml';
import {
  INSIGHT_SCHEMA_FIELDS,
  insightSchema
} from '../src/content/insight-schema.ts';
import { INSIGHT_VISUAL_THEMES } from '../src/lib/insight-visual-theme.ts';
import { getTranslations } from '../src/i18n/translations.ts';

const root = process.cwd();
const contentRoot = path.join(root, 'src/content/insights');
const publicRoot = path.join(root, 'public');
const cmsConfigPath = path.join(root, 'public/admin/config.yml');
const cmsValidationPath = path.join(
  root,
  'public/admin/insights-validation.js'
);
const locales = ['pl', 'en'];
const errors = [];
const warnings = [];

function error(message) {
  errors.push(message);
}

function warning(message) {
  warnings.push(message);
}

function readFrontmatter(source, file) {
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/u);

  if (!match) {
    error(`${file}: missing YAML frontmatter.`);
    return null;
  }

  try {
    return parse(match[1]);
  } catch (parseError) {
    error(`${file}: invalid YAML (${parseError.message}).`);
    return null;
  }
}

function formatZodIssue(issue) {
  const location = issue.path.length > 0 ? issue.path.join('.') : 'frontmatter';
  return `${location}: ${issue.message}`;
}

async function readEntries() {
  const entries = [];

  for (const folderLocale of locales) {
    const directory = path.join(contentRoot, folderLocale);
    const files = (await readdir(directory))
      .filter((file) => /\.(?:md|mdx)$/u.test(file))
      .sort();

    for (const fileName of files) {
      const absolutePath = path.join(directory, fileName);
      const relativePath = path.relative(root, absolutePath);
      const data = readFrontmatter(
        await readFile(absolutePath, 'utf8'),
        relativePath
      );

      if (!data) continue;

      const parsed = insightSchema.safeParse(data);

      if (!parsed.success) {
        for (const issue of parsed.error.issues) {
          error(`${relativePath}: ${formatZodIssue(issue)}`);
        }
        continue;
      }

      if (parsed.data.locale !== folderLocale) {
        error(
          `${relativePath}: locale "${parsed.data.locale}" does not match folder "${folderLocale}".`
        );
      }

      const fileSlug = fileName.replace(/\.(?:md|mdx)$/u, '');

      if (fileSlug !== parsed.data.slug) {
        error(
          `${relativePath}: filename slug "${fileSlug}" does not match frontmatter slug "${parsed.data.slug}".`
        );
      }

      if (parsed.data.headerImageAlt && !parsed.data.headerImage) {
        warning(
          `${relativePath}: orphan headerImageAlt will be removed by the CMS preSave hook.`
        );
      }

      for (const fieldName of ['headerImage', 'socialImage']) {
        const publicPath = parsed.data[fieldName];

        if (!publicPath) continue;

        const assetPath = path.join(publicRoot, publicPath.slice(1));

        try {
          const asset = await stat(assetPath);
          if (!asset.isFile()) {
            error(`${relativePath}: ${fieldName} is not a file (${publicPath}).`);
          }
        } catch {
          error(`${relativePath}: ${fieldName} does not exist (${publicPath}).`);
        }
      }

      entries.push({
        file: relativePath,
        folderLocale,
        data: parsed.data,
        source: await readFile(absolutePath, 'utf8')
      });
    }
  }

  return entries;
}

function checkUniqueValues(entries) {
  for (const locale of locales) {
    const localizedEntries = entries.filter(
      (entry) => entry.data.locale === locale
    );

    for (const fieldName of ['slug', 'translationKey']) {
      const seen = new Map();

      for (const entry of localizedEntries) {
        const value = entry.data[fieldName];
        const previous = seen.get(value);

        if (previous) {
          error(
            `${entry.file}: duplicate ${fieldName} "${value}" for ${locale}; already used by ${previous}.`
          );
        } else {
          seen.set(value, entry.file);
        }
      }
    }

    const publishedRoutes = new Map();

    for (const entry of localizedEntries.filter(({ data }) => !data.draft)) {
      const route = locale === 'pl'
        ? `/insights/${entry.data.slug}/`
        : `/en/insights/${entry.data.slug}/`;
      const previous = publishedRoutes.get(route);

      if (previous) {
        error(
          `${entry.file}: published route ${route} is already generated by ${previous}.`
        );
      } else {
        publishedRoutes.set(route, entry.file);
      }
    }
  }
}

function checkTranslationPairs(entries) {
  const byTranslationKey = new Map();

  for (const entry of entries) {
    const group = byTranslationKey.get(entry.data.translationKey) ?? [];
    group.push(entry);
    byTranslationKey.set(entry.data.translationKey, group);
  }

  for (const [translationKey, group] of byTranslationKey) {
    const presentLocales = new Set(group.map((entry) => entry.data.locale));

    if (presentLocales.size === 1) {
      warning(
        `translationKey "${translationKey}" has no ${presentLocales.has('pl') ? 'EN' : 'PL'} pair; the current routing correctly omits a false article hreflang.`
      );
    }
  }
}

function checkFuturePublication(entries) {
  const now = Date.now();

  for (const entry of entries) {
    if (!entry.data.draft && entry.data.publishedAt.valueOf() > now) {
      warning(
        `${entry.file}: non-draft future publishedAt is public under the current publication rule.`
      );
    }
  }
}

function contentShape(value) {
  if (Array.isArray(value)) {
    return value.map(contentShape);
  }

  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, contentShape(value[key])])
    );
  }

  return typeof value;
}

function checkBilingualCopyContract(entries) {
  const polish = getTranslations('pl');
  const english = getTranslations('en');

  if (
    JSON.stringify(contentShape(polish)) !==
    JSON.stringify(contentShape(english))
  ) {
    error('PL/EN translation structures no longer have matching keys and arrays.');
  }

  const requiredCtas = [
    ['home.hero.cta', polish.home.hero.cta, english.home.hero.cta],
    ['home.services.link', polish.home.services.link, english.home.services.link],
    ['home.experience.link', polish.home.experience.link, english.home.experience.link],
    ['home.insights.all', polish.home.insights.all, english.home.insights.all],
    ['home.contact.cta', polish.home.contact.cta, english.home.contact.cta],
    ['site.nav.contact', polish.site.nav.contact, english.site.nav.contact],
    ['contactPage.form.submit', polish.contactPage.form.submit, english.contactPage.form.submit],
    ['insightsPage.read', polish.insightsPage.read, english.insightsPage.read]
  ];

  for (const [field, ...values] of requiredCtas) {
    if (values.some((value) => typeof value !== 'string' || value.trim() === '')) {
      error(`${field} must remain non-empty in both languages.`);
    }
  }

  const removedPhrases = [
    'Najpierw kontekst. Potem rozwiązanie.',
    'Context first. Then the solution.',
    'Chaos nie musi nią być.',
    'Chaos need not be.',
    'użyteczne pod presją, a nie tylko poprawne na papierze',
    'useful under pressure, not merely correct on paper',
    'Dobre ćwiczenie kryzysowe nie jest spektaklem',
    'A good crisis exercise is not a performance'
  ];
  const searchableCopy = [
    JSON.stringify(polish),
    JSON.stringify(english),
    ...entries.map(({ source }) => source)
  ].join('\n');

  for (const phrase of removedPhrases) {
    if (searchableCopy.includes(phrase)) {
      error(`Removed high-visibility phrase returned: "${phrase}".`);
    }
  }
}

function normaliseCmsField(field) {
  return {
    name: field.name,
    widget: field.widget,
    required: field.required !== false,
    type: field.type ?? null,
    format: field.format ?? null,
    chooseUrl: field.choose_url ?? null,
    pattern: Array.isArray(field.pattern) ? field.pattern[0] : null,
    options: Array.isArray(field.options) ? field.options : null,
    child: field.field ? normaliseCmsField(field.field) : null
  };
}

function checkCmsParity(config) {
  const polish = config.collections?.find(
    (collection) => collection.name === 'insights_pl'
  );
  const english = config.collections?.find(
    (collection) => collection.name === 'insights_en'
  );

  if (!polish || !english) {
    error('CMS config must define both insights_pl and insights_en collections.');
    return;
  }

  const polishFields = polish.fields.map(normaliseCmsField);
  const englishFields = english.fields.map(normaliseCmsField);

  if (JSON.stringify(polishFields) !== JSON.stringify(englishFields)) {
    error(
      'CMS PL/EN field contracts differ in names, widgets, required flags or constraints.'
    );
  }

  const cmsFieldNames = polishFields.map(({ name }) => name).sort();
  const schemaFieldNames = [...INSIGHT_SCHEMA_FIELDS, 'body'].sort();

  if (JSON.stringify(cmsFieldNames) !== JSON.stringify(schemaFieldNames)) {
    error(
      `CMS fields do not match the Astro content contract. CMS: ${cmsFieldNames.join(', ')}; Astro: ${schemaFieldNames.join(', ')}.`
    );
  }

  for (const collection of [polish, english]) {
    for (const fieldName of ['headerImage', 'socialImage']) {
      const field = collection.fields.find(({ name }) => name === fieldName);

      if (!field || field.widget !== 'image') {
        error(`${collection.name}.${fieldName} must remain an image widget.`);
        continue;
      }

      if (field.choose_url !== false) {
        error(`${collection.name}.${fieldName} must keep choose_url: false.`);
      }

      if ('pattern' in field) {
        error(
          `${collection.name}.${fieldName} must not define pattern; this would break the Sveltia image workaround.`
        );
      }
    }

    const visualTheme = collection.fields.find(
      ({ name }) => name === 'visualTheme'
    );
    if (!visualTheme || visualTheme.widget !== 'select') {
      error(`${collection.name}.visualTheme must be an optional select widget.`);
    } else {
      if (visualTheme.required !== false) {
        error(`${collection.name}.visualTheme must remain optional.`);
      }
      if (
        JSON.stringify(visualTheme.options) !==
        JSON.stringify(INSIGHT_VISUAL_THEMES)
      ) {
        error(
          `${collection.name}.visualTheme options must match the production theme allowlist.`
        );
      }
    }
  }

  if (config.media_folder !== '/public/images/insights') {
    error('CMS media_folder must remain /public/images/insights.');
  }

  if (config.public_folder !== '/images/insights') {
    error('CMS public_folder must remain /images/insights.');
  }

  if (config.media_libraries?.stock_assets !== false) {
    error('CMS stock_assets must remain disabled.');
  }
}

async function checkCmsPreSaveHook() {
  const source = await readFile(cmsValidationPath, 'utf8');
  let listener;
  const CMS = {
    registerEventListener(candidate) {
      listener = candidate;
    }
  };

  vm.runInNewContext(source, { CMS }, { filename: cmsValidationPath });

  if (listener?.name !== 'preSave' || typeof listener.handler !== 'function') {
    error('CMS Insights validation must register a preSave listener.');
    return;
  }

  const makeEntry = (data) => ({
    get(key) {
      return key === 'collection' ? 'insights_pl' : undefined;
    },
    getIn([scope, field]) {
      return scope === 'data' ? data[field] : undefined;
    },
    deleteIn(keys) {
      return { deleted: keys };
    }
  });

  try {
    listener.handler({
      entry: makeEntry({
        headerImage: '/images/insights/valid.webp',
        headerImageAlt: 'Opis',
        socialImage: '/images/insights/social.webp'
      })
    });
  } catch {
    error('CMS preSave rejected a valid repository media path.');
  }

  try {
    listener.handler({
      entry: makeEntry({
        headerImage: '/outside/invalid.webp',
        headerImageAlt: 'Opis'
      })
    });
    error('CMS preSave accepted an image outside /images/insights/.');
  } catch {
    // Expected.
  }

  try {
    listener.handler({
      entry: makeEntry({
        headerImage: '/images/insights/valid.webp'
      })
    });
    error('CMS preSave accepted a header image without alt text.');
  } catch {
    // Expected.
  }

  const orphanResult = listener.handler({
    entry: makeEntry({
      headerImageAlt: 'Orphan alt'
    })
  });

  if (orphanResult?.deleted?.join('.') !== 'data.headerImageAlt') {
    error('CMS preSave no longer removes orphan headerImageAlt.');
  }
}

const entries = await readEntries();
checkUniqueValues(entries);
checkTranslationPairs(entries);
checkFuturePublication(entries);
checkBilingualCopyContract(entries);

const cmsConfig = parse(await readFile(cmsConfigPath, 'utf8'));
checkCmsParity(cmsConfig);
await checkCmsPreSaveHook();

for (const message of warnings) {
  console.warn(`WARN: ${message}`);
}

if (errors.length > 0) {
  console.error(`Content/CMS contract failed:\n${errors.map((item) => `- ${item}`).join('\n')}`);
  process.exit(1);
}

console.log(
  `Content/CMS contract passed for ${entries.length} Insights entries (${warnings.length} warning${warnings.length === 1 ? '' : 's'}).`
);
